modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Burgered"
authors="WiredTomato"
description='''Burgers, Burgers, & even more burgers'''

[[mixins]]
config="burgered.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.0-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId = "architectury"
    type="required"
    versionRange = "[${architectury_version},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "cloth_config"
    type="required"
    versionRange = "[15.0.128,)"
    ordering = "AFTER"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "kotlinforforge"
    type="required"
    versionRange = "[${kotlin_for_forge_version},)"
    ordering = "AFTER"
    side = "BOTH"
